/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as endUsersIndexRouteImport } from './routes/(end-users)/index'
import { Route as turfOwnerBookingsRouteImport } from './routes/(turf-owner)/bookings'
import { Route as authVerifyPhoneNumberRouteImport } from './routes/(auth)/verify-phone-number'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginScreenRouteImport } from './routes/(auth)/login-screen'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authEnterPhoneNumberRouteImport } from './routes/(auth)/enter-phone-number'
import { Route as authCompleteSignUpRouteImport } from './routes/(auth)/complete-sign-up'

const endUsersIndexRoute = endUsersIndexRouteImport.update({
  id: '/(end-users)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const turfOwnerBookingsRoute = turfOwnerBookingsRouteImport.update({
  id: '/(turf-owner)/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyPhoneNumberRoute = authVerifyPhoneNumberRouteImport.update({
  id: '/(auth)/verify-phone-number',
  path: '/verify-phone-number',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginScreenRoute = authLoginScreenRouteImport.update({
  id: '/(auth)/login-screen',
  path: '/login-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authEnterPhoneNumberRoute = authEnterPhoneNumberRouteImport.update({
  id: '/(auth)/enter-phone-number',
  path: '/enter-phone-number',
  getParentRoute: () => rootRouteImport,
} as any)
const authCompleteSignUpRoute = authCompleteSignUpRouteImport.update({
  id: '/(auth)/complete-sign-up',
  path: '/complete-sign-up',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/complete-sign-up': typeof authCompleteSignUpRoute
  '/enter-phone-number': typeof authEnterPhoneNumberRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login-screen': typeof authLoginScreenRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-phone-number': typeof authVerifyPhoneNumberRoute
  '/bookings': typeof turfOwnerBookingsRoute
  '/': typeof endUsersIndexRoute
}
export interface FileRoutesByTo {
  '/complete-sign-up': typeof authCompleteSignUpRoute
  '/enter-phone-number': typeof authEnterPhoneNumberRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login-screen': typeof authLoginScreenRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-phone-number': typeof authVerifyPhoneNumberRoute
  '/bookings': typeof turfOwnerBookingsRoute
  '/': typeof endUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/complete-sign-up': typeof authCompleteSignUpRoute
  '/(auth)/enter-phone-number': typeof authEnterPhoneNumberRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login-screen': typeof authLoginScreenRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/verify-phone-number': typeof authVerifyPhoneNumberRoute
  '/(turf-owner)/bookings': typeof turfOwnerBookingsRoute
  '/(end-users)/': typeof endUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/complete-sign-up'
    | '/enter-phone-number'
    | '/forgot-password'
    | '/login-screen'
    | '/reset-password'
    | '/verify-phone-number'
    | '/bookings'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/complete-sign-up'
    | '/enter-phone-number'
    | '/forgot-password'
    | '/login-screen'
    | '/reset-password'
    | '/verify-phone-number'
    | '/bookings'
    | '/'
  id:
    | '__root__'
    | '/(auth)/complete-sign-up'
    | '/(auth)/enter-phone-number'
    | '/(auth)/forgot-password'
    | '/(auth)/login-screen'
    | '/(auth)/reset-password'
    | '/(auth)/verify-phone-number'
    | '/(turf-owner)/bookings'
    | '/(end-users)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authCompleteSignUpRoute: typeof authCompleteSignUpRoute
  authEnterPhoneNumberRoute: typeof authEnterPhoneNumberRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginScreenRoute: typeof authLoginScreenRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authVerifyPhoneNumberRoute: typeof authVerifyPhoneNumberRoute
  turfOwnerBookingsRoute: typeof turfOwnerBookingsRoute
  endUsersIndexRoute: typeof endUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(end-users)/': {
      id: '/(end-users)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof endUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(turf-owner)/bookings': {
      id: '/(turf-owner)/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof turfOwnerBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-phone-number': {
      id: '/(auth)/verify-phone-number'
      path: '/verify-phone-number'
      fullPath: '/verify-phone-number'
      preLoaderRoute: typeof authVerifyPhoneNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login-screen': {
      id: '/(auth)/login-screen'
      path: '/login-screen'
      fullPath: '/login-screen'
      preLoaderRoute: typeof authLoginScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/enter-phone-number': {
      id: '/(auth)/enter-phone-number'
      path: '/enter-phone-number'
      fullPath: '/enter-phone-number'
      preLoaderRoute: typeof authEnterPhoneNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/complete-sign-up': {
      id: '/(auth)/complete-sign-up'
      path: '/complete-sign-up'
      fullPath: '/complete-sign-up'
      preLoaderRoute: typeof authCompleteSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  authCompleteSignUpRoute: authCompleteSignUpRoute,
  authEnterPhoneNumberRoute: authEnterPhoneNumberRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginScreenRoute: authLoginScreenRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authVerifyPhoneNumberRoute: authVerifyPhoneNumberRoute,
  turfOwnerBookingsRoute: turfOwnerBookingsRoute,
  endUsersIndexRoute: endUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
